name: "test"

on: [push]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: 5.4
    - uses: leafo/gh-actions-luarocks@v4.0.0
    - name: Install busted
      run: luarocks install busted
    - name: Install dependencies
      run: luarocks make rockspecs/nelua-dev-1.rockspec
    - name: Test
      run: CC=clang busted -o utfTerminal
